### ISSUE TITLE
Xenial next steps

### ISSUE THREAD

**Issue by edmorley** [travis-ci/packer-templates#575]
I likely won't have any more time for the Xenial work, so filing this to make it easier for others to take the next steps. Feel free to edit this post to add/update todo items as needed :-)

**TODO (after the work in #549, #554 and #562):**
- [ ] Debug/fix the cause of the Xenial Docker builds timing out during the rabbitmq-server install (it works fine for the GCE builds). For my initial findings, see #562.
- [ ] Fix php-src-builder on Xenial (see travis-ci/travis-ci#8737), trigger appropriate builds, and then re-enable PHP in this repo (see changes in #549 and #554 for what to revert).
- [ ] Fix travis-erlang-builder on Xenial (see travis-ci/travis-erlang-builder#6), trigger appropriate builds, and then re-enable Erlang/OTP in this repo (see changes in #549 and #554 for what to revert).
- [ ] Decide whether the phantomjs v1 builds should be fixed or whether phantomjs v2 only support is fine. Then either create a build for Xenial and re-enable (see changes in #549 and #554 for what to revert), or else remove the TODOs and check the tests here and in travis-cookbooks are run against v2 correctly.
- [ ] Decide whether openjdk7 still needs to be included in the images for Xenial (rather than only newer versions), and if so, revert the change [here](https://github.com/travis-ci/packer-templates/pull/549/files#diff-148658cbc43694872fb0a44117795a20L53) and fix the build.
- [ ] Decide whether #562's choice of fix ("option 1") for #544 is what is desired longer term (see https://github.com/travis-ci/packer-templates/issues/544#issuecomment-344971947) and if so remove the TODOs, or else switch to one of the alternatives.
- [ ] Decide what to do with the failing openstack builds (see #555), which were temporarily commented out in #562.
